# Site
name: 'PASC research'
description: 'PASC research team description'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: www.youtube.com

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    yong:
      name:           Yong Huang
      site:           https://yonglhuang.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Bio"
      email:          yongh7@uci.edu
      twitter:        https://twitter.com


resources:
    cdc:
      name:           Centers for Disease Control and Prevention
      site:           https://www.cdc.gov
      avatar:         /assets/images/avatar1.jpg
      bio:            "Centers for Disease Control and Prevention"
      twitter:        https://twitter.com
      
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: doe
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]


